### ISSUE TITLE
Es gibt bei uns einen Fehler mit dem letzten Attributset bzw. wenn es nur *ein* Attributset gibt.

### ISSUE THREAD

**Issue by oligoform** [leofonic/oxid_extfilter#2]
...dann greift das Modul nicht mehr und es wird doch wieder nur noch der eine gewählte Attribut-Wert angezeigt. 
Beim Zurücksetzen des Filters kommt es dann sogar zu einem "undefinierten" Zustand: Es werden keine Attribut-Werte mehr angezeigt & man kann die Filter erst nach löschen der "Filter-Session" wieder nutzen.

tritt das nur in unseren Installationen auf, oder kann das jemand bestätigen?

**Comment by oligoform** [comment]
bei bedarf können wir einen Pull Request schicken :)

**Comment by leofonic** [comment]
Gerne!

**Comment by oligoform** [comment]
ist das Phänomen bei euch auch schon mal aufgetreten?

**Comment by leofonic** [comment]
Hab das behoben, lag an einem leeren Filterarray.
